Task10 c
Alinafrolova05/2023-cpp-autumn pull request #13
Opened 2024-12-22 20:45 UTC by Alinafrolova05

2024-12-28 18:23 UTC, yurii-litvinov requested changes

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +void listOf(FILE* file, Graphs* table, int n) {
listOf что? Я правда без идей, почему функция, читающая граф из файла, называется listOf :) И что за n

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +        sscanf(buffer, "%d %d %d", &from, &to, &weight);
Можно было прямо из файла fscanf-ом читать

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +    int* visited = (int*)calloc(n, sizeof(int));
Наверное, visited мог бы быть bool

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +void algorithm(Graphs* table, int n, int* capitals, Graphs* state, int k) {
Это тоже надо как-то более мнемонично называть

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +    int* anotherArray = (int*)calloc(max, sizeof(int));
Такая себе сортировка подсчётом, не умеет отрицательные числа и очень большие, но близкие числа :)

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +    int check = 0;
Это тоже могло бы быть булевым и называться получше

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +#define INT_MAX 100
Оу. Есть библиотечный макрос INT_MAX, и он побольше. Это как в анекдоте про `#define true false // Удачной отладки, лохи` :)

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +    int visited[128] = { 0 };
Почему 128?

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +        dijkstra(table, capitals[i % k], n, distances);
В условии просили добавлять город с минимальной дистанцией до государства, не до столицы

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +        dijkstra(table, capitals[i % k], n, distances);
И Дейкстра тут не нужна, потому что ближайший к государству город очевидно находится на границе государства, так что достаточно просто найти минимальное из всех рёбер, ведущих из какого-либо города государства в любой незанятый город

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.c
> +        countingSort(n, distances);
Никто не обещал, что условия для countingSort подходящие. Например, длины всех дорого могут быть 4 миллиарда, почему нет :)

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.h
> +} Graphs;
Это нельзя в .h, нарушение принципа сокрытия данных

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.h
> +void push(Graphs** element1, int number, int weight);
Нужны комментарии ко всему, что есть в .h

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/functions.h
> +#ifndef TREE
???

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/graphs.c
> +    else if (!testSort()) {
Тесты на сам алгоритм бы ещё. Ну и точно тесты имеют смысл до того, как файл открывается.

2024-12-28 18:23 UTC, yurii-litvinov commented on graphs/graphs.c
> +    }
Зачитывание из файла всей информации я бы тоже в отдельную функцию вынес, и проверял бы в тестах. Тут какой-то нетривиальный код, в нём могут быть ошибки

2025-01-17 18:49 UTC, closed without merging

2025-02-12 21:41 UTC, Alinafrolova05 commented on test/Task3/Task3.c
> -﻿#pragma once
А почему удалит?